{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "astis-workload-secrets.namespace" . }}
  labels:
    {{- include "astis-workload-secrets.labels" . | nindent 4 }}
{{- end }}
